---
name: _build
on:
  workflow_call:
    inputs:
      build_matrix:
        required: true
        type: string
        description: Build matrix for the build job
      build_type:
        required: false
        type: string
        default: "flat_build"
        description: Type of build to perform (flat_build or sdk_build)

jobs:
  build:
    runs-on:
      group: GHA-Audioreach-SelfHosted-RG
      labels: [ self-hosted, audior-prd-u22-sdk-x64-large-od-ephem ]
    strategy:
      fail-fast: false
      matrix:
        build_matrix: ${{ fromJson(inputs.build_matrix) }}
    steps:
      - name: Build docker Image
        id: get-docker-image
        uses: Audioreach/meta-audioreach/.github/actions/build_docker_image@master

      - name: Sync Codebase
        id: sync
        uses: Audioreach/meta-audioreach/.github/actions/sync@master
        with:
          event_name: ${{ github.event_name }}
          pr_ref: ${{ github.event.pull_request.head.ref }}
          pr_repo: ${{ github.event.pull_request.head.repo.full_name }}
          base_ref: ${{ github.ref_name }}

      # Use build command from matrix
      - name: Build for ${{ matrix.build_matrix.machine_name }}
        uses: Audioreach/meta-audioreach/.github/actions/build@master
        with:
          docker_image: ${{ steps.get-docker-image.outputs.image_name }}
          kas_file: ${{ matrix.build_matrix.kas_file }}
          machine_name: ${{ matrix.build_matrix.machine_name }}
          build_command: ${{ matrix.build_matrix.build_commands[inputs.build_type] }}  # Get command from matrix based on build type
          build_type: ${{ inputs.build_type }}
          image_name: ${{ matrix.build_matrix.image_name }}
        env:
          MACHINE: ${{ matrix.build_matrix.machine_name }}

      - name: Cleanup Workspace
        if: always()
        run: |
          rm -rf "${GITHUB_WORKSPACE}/../build"
          rm -rf pub
          echo "Workspace cleaned up."
