name: pre_merge_build
run-name: Pre Merge Build ${{ github.event.pull_request.number != '' && github.event.pull_request.number || '' }}

on:
  workflow_dispatch:
    inputs:
      testplan:
        description: 'Test plan name to use in job generation (lava-test-plans)'
        required: false
        type: string
        default: 'pre-merge'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
    paths-ignore:
      - '.github/**'

jobs:
  load_parameters:
    uses: ./.github/workflows/loading.yml

  flat_build:
    needs: load_parameters
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      build_matrix: ${{ needs.load_parameters.outputs.build_matrix }}
      build_type: flat_build

  filter_test_matrix:
    needs: load_parameters
    runs-on: ubuntu-latest
    outputs:
      test_matrix: ${{ steps.filter.outputs.test_matrix }}
    steps:
      - id: filter
        shell: bash
        run: |
          MATRIX="${NEEDS_LOAD_PARAMETERS_OUTPUTS_BUILD_MATRIX}"
          echo "RAW build_matrix:"
          echo "$MATRIX"
          echo "Validating JSON..."
          echo "$MATRIX" | jq . >/dev/null

          FILTERED=$(
            echo "$MATRIX" | jq -c '
            if type == "object" then
              to_entries
              | map(select(.value.testing_enabled == true))
              | from_entries
            elif type == "array" then
              map(select(.testing_enabled == true))
            else
              error("Unsupported build_matrix JSON type: " + (type|tostring))
            end
            '
          )

          echo "Filtered matrix (pretty):"
          echo "$FILTERED" | jq .
          echo "$FILTERED" > test_matrix.json
          echo "test_matrix=$FILTERED" >> "$GITHUB_OUTPUT"
        env:
          NEEDS_LOAD_PARAMETERS_OUTPUTS_BUILD_MATRIX: ${{ needs.load_parameters.outputs.build_matrix }}

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: test-matrix
          path: test_matrix.json
